name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run build script
        run: ./build.sh

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}-${{ github.sha }}
          name: "Release ${{ github.run_number }}"
          body: "Automated release based on commit ${{ github.sha }}"
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}